# Generated by Django 4.2.30 on 2026-06-08 10:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('niveau', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('centres_interet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('idCompetence', models.AutoField(primary_key=True, serialize=False)),
                ('nomCompetence', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'competence',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('idFiliere', models.AutoField(primary_key=True, serialize=False)),
                ('nomFiliere', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'filiere',
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('idDisponibilite', models.AutoField(primary_key=True, serialize=False)),
                ('jourDisponibilite', models.CharField(max_length=255)),
                ('heure_debutDisponibilite', models.TimeField()),
                ('heure_finDisponibilite', models.TimeField()),
                ('statutDisponibilite', models.CharField(max_length=255)),
                ('date_creationDisponibilite', models.DateTimeField(auto_now_add=True)),
                ('date_modificationDisponibilite', models.DateTimeField(auto_now=True)),
                ('idUtilisateur', models.ForeignKey(db_column='idUtilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disponibilite',
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='filiere',
            field=models.ForeignKey(blank=True, db_column='idFiliere', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.filiere'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UtilisateurCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeUtilisateur_Competence', models.CharField(max_length=255)),
                ('idCompetence', models.ForeignKey(db_column='idCompetence', on_delete=django.db.models.deletion.CASCADE, to='accounts.competence')),
                ('idUtilisateur', models.ForeignKey(db_column='idUtilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'utilisateur_competence',
                'unique_together': {('idUtilisateur', 'idCompetence')},
            },
        ),
    ]
