# Generated by Django 4.2.30 on 2026-06-08 13:33

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='bio',
            field=models.TextField(blank=True, db_column='bioUtilisateur', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='centres_interet',
            field=models.TextField(blank=True, db_column='centres_interetUtilisateur', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(db_column='date_CreationUtilisateur', default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, db_column='emailUtilisateur', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(blank=True, db_column='nomUtilisateur', max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(db_column='idUtilisateur', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(blank=True, db_column='prenomUtilisateur', max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='niveau',
            field=models.CharField(blank=True, db_column='niveauUtilisateur', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(db_column='mot_de_passeUtilisateur', max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, db_column='photoUtilisateur', null=True, upload_to='profils/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, db_column='telephoneUtilisateur', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, db_column='username', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
