# Generated by Django 4.2.30 on 2026-06-10 23:09

from django.db import migrations

def insert_filieres(apps, schema_editor):
    Filiere = apps.get_model('accounts', 'Filiere')
    filieres = [
        {'idFiliere': 1, 'nomFiliere': 'GL'},
        {'idFiliere': 2, 'nomFiliere': 'IM'},
        {'idFiliere': 3, 'nomFiliere': 'SI'},
        {'idFiliere': 4, 'nomFiliere': 'IA'},
        {'idFiliere': 5, 'nomFiliere': 'IOT'},
    ]
    for f in filieres:
        Filiere.objects.get_or_create(idFiliere=f['idFiliere'], defaults={'nomFiliere': f['nomFiliere']})

def delete_filieres(apps, schema_editor):
    Filiere = apps.get_model('accounts', 'Filiere')
    Filiere.objects.filter(idFiliere__in=[1, 2, 3, 4, 5]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.RunPython(insert_filieres, delete_filieres),
    ]
