# Generated by Django 4.2.30 on 2026-06-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('idAnnonce', models.AutoField(primary_key=True, serialize=False)),
                ('typeAnnonce', models.CharField(max_length=255)),
                ('formatAnnonce', models.CharField(max_length=255)),
                ('statutAnnonce', models.CharField(max_length=255)),
                ('date_creationAnnonce', models.DateTimeField(auto_now_add=True)),
                ('date_modificationAnnonce', models.DateTimeField(auto_now=True)),
                ('idUtilisateur', models.ForeignKey(db_column='idUtilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annonce',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('idMatches', models.AutoField(primary_key=True, serialize=False)),
                ('score_compatibiliteMatch', models.FloatField()),
                ('statutMatches', models.CharField(max_length=255)),
                ('date_creationMatches', models.DateTimeField(auto_now_add=True)),
                ('date_modificationMatches', models.DateTimeField(auto_now=True)),
                ('idMentor', models.ForeignKey(db_column='idMentor', on_delete=django.db.models.deletion.CASCADE, related_name='matchs_mentor', to=settings.AUTH_USER_MODEL)),
                ('idMentore', models.ForeignKey(db_column='idMentore', on_delete=django.db.models.deletion.CASCADE, related_name='matchs_mentore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='AnnonceDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAnnonce', models.ForeignKey(db_column='idAnnonce', on_delete=django.db.models.deletion.CASCADE, to='matching.annonce')),
                ('idDisponibilite', models.ForeignKey(db_column='idDisponibilite', on_delete=django.db.models.deletion.CASCADE, to='accounts.disponibilite')),
            ],
            options={
                'db_table': 'annonce_disponibilite',
                'unique_together': {('idAnnonce', 'idDisponibilite')},
            },
        ),
        migrations.CreateModel(
            name='AnnonceCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAnnonce', models.ForeignKey(db_column='idAnnonce', on_delete=django.db.models.deletion.CASCADE, to='matching.annonce')),
                ('idCompetence', models.ForeignKey(db_column='idCompetence', on_delete=django.db.models.deletion.CASCADE, to='accounts.competence')),
            ],
            options={
                'db_table': 'annonce_competence',
                'unique_together': {('idAnnonce', 'idCompetence')},
            },
        ),
    ]
