# Generated by Django 4.2.30 on 2026-06-09 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annoncecompetence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='annoncecompetence',
            name='idAnnonce',
        ),
        migrations.RemoveField(
            model_name='annoncecompetence',
            name='idCompetence',
        ),
        migrations.AlterUniqueTogether(
            name='annoncedisponibilite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='annoncedisponibilite',
            name='idAnnonce',
        ),
        migrations.RemoveField(
            model_name='annoncedisponibilite',
            name='idDisponibilite',
        ),
        migrations.AlterField(
            model_name='match',
            name='idMentor',
            field=models.ForeignKey(db_column='idMentor', on_delete=django.db.models.deletion.CASCADE, related_name='matches_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='idMentore',
            field=models.ForeignKey(db_column='idMentore', on_delete=django.db.models.deletion.CASCADE, related_name='matches_mentore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Annonce',
        ),
        migrations.DeleteModel(
            name='AnnonceCompetence',
        ),
        migrations.DeleteModel(
            name='AnnonceDisponibilite',
        ),
    ]
