# Generated by Django 4.2.30 on 2026-06-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('idConversation', models.AutoField(primary_key=True, serialize=False)),
                ('date_creationConversation', models.DateTimeField(auto_now_add=True)),
                ('idMatches', models.ForeignKey(db_column='idMatches', on_delete=django.db.models.deletion.CASCADE, to='matching.match')),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idMessage', models.AutoField(primary_key=True, serialize=False)),
                ('contenuMessage', models.TextField()),
                ('luMessage', models.BooleanField(default=False)),
                ('date_creationMessage', models.DateTimeField(auto_now_add=True)),
                ('idConversation', models.ForeignKey(db_column='idConversation', on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation')),
                ('id_expediteurMessage', models.ForeignKey(db_column='id_expediteurMessage', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
